#!/bin/bash

CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-docker}"

# Skip the image build and use a host mounted volume to get up to date code
FAST=${FAST:-0}

cd "$(dirname "$0")" || exit

if [[ $FAST -eq 0 ]]; then
  $CONTAINER_RUNTIME build -t data-transfer-test -f ../Dockerfile.test --build-arg install_flags="" .. || exit 1
fi

if [[ $FAST -eq 1 ]]; then
  DOCKER_ARGS="${DOCKER_ARGS} -v $(pwd)/../acapy_plugin_data_transfer:/home/indy/acapy_plugin_data_transfer:z"
  DOCKER_ARGS="${DOCKER_ARGS} -v $(pwd)/../tests:/home/indy/tests:z"
fi

# on Windows, docker run needs to be prefixed by winpty
if [ "$OSTYPE" == "msys" ]; then
  CONTAINER_RUNTIME="winpty docker"
fi

$CONTAINER_RUNTIME run --rm -ti --name data-transfer-test \
    $DOCKER_ARGS --entrypoint pytest data-transfer-test "$@"
